# Generated by Django 4.2.7 on 2025-06-27 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedback_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rating_1', models.IntegerField(blank=True, null=True)),
                ('rating_2', models.IntegerField(blank=True, null=True)),
                ('rating_3', models.IntegerField(blank=True, null=True)),
                ('rating_4', models.IntegerField(blank=True, null=True)),
                ('rating_5', models.IntegerField(blank=True, null=True)),
                ('rating_6', models.IntegerField(blank=True, null=True)),
                ('rating_7', models.IntegerField(blank=True, null=True)),
                ('rating_8', models.IntegerField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='rating_1',
            field=models.IntegerField(help_text='The training met my expectations', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Met Expectations'),
        ),
    ]
