# Generated by Django 5.2.3 on 2025-07-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackimage_trainingsession_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(blank=True, max_length=100)),
                ('rating_1', models.IntegerField()),
                ('rating_2', models.IntegerField()),
                ('rating_3', models.IntegerField()),
                ('rating_4', models.IntegerField()),
                ('rating_5', models.IntegerField()),
                ('rating_6', models.IntegerField()),
                ('rating_7', models.IntegerField()),
                ('rating_8', models.IntegerField()),
                ('key_learnings', models.TextField(blank=True)),
                ('missing_elements', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
