# Generated by Django 5.2.3 on 2025-07-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.trainingsession'),
        ),
    ]
